### PR TITLE
Set force_destroy on child zone

### PR DESCRIPTION
**Pull request by jmervine**

### CODE REVIEW

**Review by sheax0r — CHANGES_REQUESTED** [review]
@jmervine thanks for doing this - a few comments:

1. Can you use `terraform-docs` to regenerate the docs for [this section of the README](https://github.com/heroku/terraform-route53-to-route53-forward/#inputs)? I want to avoid having the docs get out-of-date. It's a manual process; run `terraform-docs md .`, then copy-pasta what you need into README.md.
2. I presume this is tested live, in some capacity? If not, I'll want to test it before merging (I'm happy to do that myself). Just let me know if it needs testing.

**Comment by jmervine** [comment]
I haven’t tested it, but I will. I’ll also generate the docs tomorrow.

**Comment by jmervine** [comment]
Added docs.

In my sources I did a terraform apply using this version of the module and it was a noop as expected. I really don't want to destroy my env right now. If that's not good enough, let me know and I'll attempt to test this more completely using just this module.

**Review by sheax0r — APPROVED** [review]

**Comment by sheax0r** [comment]
@jmervine I think as long as it's not causing terraform errors when you use it in a plan or apply, it's likely safe; terraform will be unhappy if you're using an invalid property for the resource. I'm sure you'll be the first person to run into a problem if there is one, anyway, so if that happens you can submit another PR :).

**Pull request merged**
